# Generated by Django 5.2 on 2026-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('B', 'Buyer'), ('V', 'Vendor'), ('W', 'Blogger')], default='B', max_length=1),
        ),
    ]
